### ISSUE TITLE
Adding/removing/renaming a new class always forces clients of that source file to be recompiled

### ISSUE THREAD

**Issue by harrah** [gkossakowski/sbt#8]
`A.scala`

``` scala
// class Q

object A { val x = 3 }
```

`B.scala`

``` scala
object B { val x = A.x }
```
1. `compile`
2. Uncomment line in A.scala.
3. `compile`.  Both sources are recompiled because Q introduces a change to the hash for `<init>`.

**Comment by gkossakowski** [comment]
Migrated to sbt/sbt#2319.
